apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --file docker-compose.keratin_authn.yaml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: "{{ .Values.service.externalPort }}"
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    io.kompose.service: {{ .Chart.Name }}
status:
  loadBalancer: {}
