apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml -f docker-compose.authn.yaml -f docker-compose.merchant.dep.yaml
      -f docker-compose.shopper.dep.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
	{{- include "auth-service.labels" . | nindent 4 }}
    io.kompose.service: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  progressDeadlineSeconds: {{ .Values.progressDeadlineInSeconds }}
  {{- if not .Values.hpa.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      io.kompose.service: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.deploymentStrategy.maxSurge }}
      maxUnavailable: {{ .Values.deploymentStrategy.maxUnavailable }}
    type: {{ .Values.deploymentStrategy.type }}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yaml -f docker-compose.authn.yaml -f
          docker-compose.merchant.dep.yaml -f docker-compose.shopper.dep.yaml convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Chart.Name }}
    spec:
      containers:
        - args:
            - sh
            - -c
            - ./authn migrate && ./authn server
          env:
            - name: ACCESS_TOKEN_TTL
              value: "86400"
            - name: APP_DOMAINS
              value: localhost
            - name: AUTHN_ACCESS_TOKEN_TTL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_ACCESS_TOKEN_TTL
                  name: auth-service-env
            - name: AUTHN_APP_PASSWORD_CHANGED_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_APP_PASSWORD_CHANGED_URL
                  name: auth-service-env
            - name: AUTHN_APP_PASSWORD_RESET_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_APP_PASSWORD_RESET_URL
                  name: auth-service-env
            - name: AUTHN_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_DATABASE_URL
                  name: auth-service-env
            - name: AUTHN_DB_ENCRYPTION_KEY_SALT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_DB_ENCRYPTION_KEY_SALT
                  name: auth-service-env
            - name: AUTHN_DOMAINS
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_DOMAINS
                  name: auth-service-env
            - name: AUTHN_ENABLE_SIGNUP
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_ENABLE_SIGNUP
                  name: auth-service-env
            - name: AUTHN_EXTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_EXTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_INTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_ISSUER_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_ISSUER_BASE_URL
                  name: auth-service-env
            - name: AUTHN_MYSQL_EXTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_MYSQL_EXTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_MYSQL_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_MYSQL_INTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_MYSQL_NAME
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_MYSQL_NAME
                  name: auth-service-env
            - name: AUTHN_ORIGIN
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_ORIGIN
                  name: auth-service-env
            - name: AUTHN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_PASSWORD
                  name: auth-service-env
            - name: AUTHN_PASSWORD_CHANGE_LOGOUT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_PASSWORD_CHANGE_LOGOUT
                  name: auth-service-env
            - name: AUTHN_PASSWORD_POLICY_SCORE
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_PASSWORD_POLICY_SCORE
                  name: auth-service-env
            - name: AUTHN_PASSWORD_RESET_TOKEN_TTL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_PASSWORD_RESET_TOKEN_TTL
                  name: auth-service-env
            - name: AUTHN_POSTGRES_CONTAINER
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_POSTGRES_CONTAINER
                  name: auth-service-env
            - name: AUTHN_POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_POSTGRES_DB_NAME
                  name: auth-service-env
            - name: AUTHN_POSTGRES_EXTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_POSTGRES_EXTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_POSTGRES_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_POSTGRES_INTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_POSTGRES_PASSWORD
                  name: auth-service-env
            - name: AUTHN_POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_POSTGRES_USER
                  name: auth-service-env
            - name: AUTHN_PRIVATE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_PRIVATE_BASE_URL
                  name: auth-service-env
            - name: AUTHN_PUBLIC_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_PUBLIC_BASE_URL
                  name: auth-service-env
            - name: AUTHN_REDIS_EXTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_REDIS_EXTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_REDIS_INTERNAL_PORT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_REDIS_INTERNAL_PORT
                  name: auth-service-env
            - name: AUTHN_REDIS_NAME
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_REDIS_NAME
                  name: auth-service-env
            - name: AUTHN_REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_REDIS_URL
                  name: auth-service-env
            - name: AUTHN_REFRESH_TOKEN_TTL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_REFRESH_TOKEN_TTL
                  name: auth-service-env
            - name: AUTHN_SECRET
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_SECRET
                  name: auth-service-env
            - name: AUTHN_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_SERVICE_NAME
                  name: auth-service-env
            - name: AUTHN_SESSION_KEY_SALT
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_SESSION_KEY_SALT
                  name: auth-service-env
            - name: AUTHN_URL
              value: http://localhost:8000
            - name: AUTHN_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_USERNAME
                  name: auth-service-env
            - name: AUTHN_USERNAME_IS_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: AUTHN_USERNAME_IS_EMAIL
                  name: auth-service-env
            - name: BACKEND_SERVICE_URLS
              valueFrom:
                configMapKeyRef:
                  key: BACKEND_SERVICE_URLS
                  name: auth-service-env
            - name: CACHE_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: CACHE_SERVER_ADDRESS
                  name: auth-service-env
            - name: CERT_PATH
              valueFrom:
                configMapKeyRef:
                  key: CERT_PATH
                  name: auth-service-env
            - name: CONFIG_FILE
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_FILE
                  name: auth-service-env
            - name: CONFIG_PATH
              valueFrom:
                configMapKeyRef:
                  key: CONFIG_PATH
                  name: auth-service-env
            - name: DATABASE_URL
              value: postgres://authentication_service:authentication_service@auth-service-db:5432/authentication_service?sslmode=disable
            - name: DATA_LOADED_IN_MEMORY_FOR_STRESS_TEST_IN_MB
              valueFrom:
                configMapKeyRef:
                  key: DATA_LOADED_IN_MEMORY_FOR_STRESS_TEST_IN_MB
                  name: auth-service-env
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  key: DATA_PATH
                  name: auth-service-env
            - name: DB_ENCRYPTION_KEY_SALT
              value: feelguuds
            - name: DOWNSTREAM_SERVICE_CONNECTION_LIMIT
              valueFrom:
                configMapKeyRef:
                  key: DOWNSTREAM_SERVICE_CONNECTION_LIMIT
                  name: auth-service-env
            - name: ENABLE_AUTHN_PRIVATE_INTEGRATION
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_AUTHN_PRIVATE_INTEGRATION
                  name: auth-service-env
            - name: ENABLE_CPU_STRESS_TEST
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_CPU_STRESS_TEST
                  name: auth-service-env
            - name: ENABLE_H2C
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_H2C
                  name: auth-service-env
            - name: ENABLE_MEMORY_STRESS_TEST
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_MEMORY_STRESS_TEST
                  name: auth-service-env
            - name: ENABLE_RANDOM_DELAY
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_RANDOM_DELAY
                  name: auth-service-env
            - name: ENABLE_RANDOM_ERROR
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_RANDOM_ERROR
                  name: auth-service-env
            - name: ENABLE_SIGNUP
              value: "false"
            - name: ENABLE_VERSION_FROM_FILE
              valueFrom:
                configMapKeyRef:
                  key: ENABLE_VERSION_FROM_FILE
                  name: auth-service-env
            - name: GRPC_CERT_PATH
              valueFrom:
                configMapKeyRef:
                  key: GRPC_CERT_PATH
                  name: auth-service-env
            - name: GRPC_ENABLE_TLS
              valueFrom:
                configMapKeyRef:
                  key: GRPC_ENABLE_TLS
                  name: auth-service-env
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  key: GRPC_PORT
                  name: auth-service-env
            - name: GRPC_RPC_DEADLINE_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: GRPC_RPC_DEADLINE_IN_MS
                  name: auth-service-env
            - name: GRPC_RPC_RETRIES
              valueFrom:
                configMapKeyRef:
                  key: GRPC_RPC_RETRIES
                  name: auth-service-env
            - name: GRPC_RPC_RETRY_BACKOFF_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: GRPC_RPC_RETRY_BACKOFF_IN_MS
                  name: auth-service-env
            - name: GRPC_RPC_RETRY_TIMEOUT_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: GRPC_RPC_RETRY_TIMEOUT_IN_MS
                  name: auth-service-env
            - name: GRPC_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  key: GRPC_SERVICE_NAME
                  name: auth-service-env
            - name: HTTPS_PORT
              valueFrom:
                configMapKeyRef:
                  key: HTTPS_PORT
                  name: auth-service-env
            - name: HTTP_AUTH_PASSWORD
              value: feelguuds
            - name: HTTP_AUTH_USERNAME
              value: feelguuds
            - name: HTTP_CLIENT_TIMEOUT_IN_MINUTES
              valueFrom:
                configMapKeyRef:
                  key: HTTP_CLIENT_TIMEOUT_IN_MINUTES
                  name: auth-service-env
            - name: HTTP_MAX_RETRIES
              valueFrom:
                configMapKeyRef:
                  key: HTTP_MAX_RETRIES
                  name: auth-service-env
            - name: HTTP_MAX_RETRY_WAIT_TIME_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: HTTP_MAX_RETRY_WAIT_TIME_IN_MS
                  name: auth-service-env
            - name: HTTP_MIN_RETRY_WAIT_TIME_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: HTTP_MIN_RETRY_WAIT_TIME_IN_MS
                  name: auth-service-env
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  key: HTTP_PORT
                  name: auth-service-env
            - name: HTTP_REQUEST_TIMEOUT_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: HTTP_REQUEST_TIMEOUT_IN_MS
                  name: auth-service-env
            - name: HTTP_SERVER_SHUTDOWN_TIMEOUT_IN_SECONDS
              valueFrom:
                configMapKeyRef:
                  key: HTTP_SERVER_SHUTDOWN_TIMEOUT_IN_SECONDS
                  name: auth-service-env
            - name: HTTP_SERVER_TIMEOUT_IN_SECONDS
              valueFrom:
                configMapKeyRef:
                  key: HTTP_SERVER_TIMEOUT_IN_SECONDS
                  name: auth-service-env
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  key: LOG_LEVEL
                  name: auth-service-env
            - name: METRICS_PORT
              valueFrom:
                configMapKeyRef:
                  key: METRICS_PORT
                  name: auth-service-env
            - name: METRIC_CONNECTION_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: METRIC_CONNECTION_ADDRESS
                  name: auth-service-env
            - name: NUMBER_OF_STRESSED_CPU
              valueFrom:
                configMapKeyRef:
                  key: NUMBER_OF_STRESSED_CPU
                  name: auth-service-env
            - name: PASSWORD_CHANGE_LOGOUT
              value: "true"
            - name: PASSWORD_POLICY_SCORE
              value: "2"
            - name: PASSWORD_RESET_TOKEN_TTL
              value: "1800"
            - name: PRIVATE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: PRIVATE_BASE_URL
                  name: auth-service-env
            - name: RANDOM_DELAY_MAX_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: RANDOM_DELAY_MAX_IN_MS
                  name: auth-service-env
            - name: RANDOM_DELAY_MIN_IN_MS
              valueFrom:
                configMapKeyRef:
                  key: RANDOM_DELAY_MIN_IN_MS
                  name: auth-service-env
            - name: RANDOM_DELAY_UNIT
              valueFrom:
                configMapKeyRef:
                  key: RANDOM_DELAY_UNIT
                  name: auth-service-env
            - name: REDIS_URL
              value: redis://auth-service-redis:6379/11
            - name: REFRESH_TOKEN_TTL
              value: "2592000"
            - name: SECRET_KEY_BASE
              value: secret
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  key: SERVICE_NAME
                  name: auth-service-env
            - name: SESSION_KEY_SALT
              value: feelguuds
            - name: SET_SERVICE_UNHEALTHY
              valueFrom:
                configMapKeyRef:
                  key: SET_SERVICE_UNHEALTHY
                  name: auth-service-env
            - name: SET_SERVICE_UNREADY
              valueFrom:
                configMapKeyRef:
                  key: SET_SERVICE_UNREADY
                  name: auth-service-env
            - name: UI_COLOR
              valueFrom:
                configMapKeyRef:
                  key: UI_COLOR
                  name: auth-service-env
            - name: UI_LOGO
              valueFrom:
                configMapKeyRef:
                  key: UI_LOGO
                  name: auth-service-env
            - name: UI_MESSAGE
              valueFrom:
                configMapKeyRef:
                  key: UI_MESSAGE
                  name: auth-service-env
            - name: UI_PATH
              valueFrom:
                configMapKeyRef:
                  key: UI_PATH
                  name: auth-service-env
            - name: USERNAME_IS_EMAIL
              value: "true"
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8000
            failureThreshold: {{ .Values.failures.failurethreshold }}
            periodSeconds: {{ .Values.failures.periodSeconds }}
            successThreshold: {{ .Values.failures.successThresholds }}
            timeoutSeconds: {{ .Values.failures.timeoutSeconds }}
          name: {{ .Chart.Name }}
          ports:
            - containerPort: {{ .Values.service.externalPort}}
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      schedulerName: {{ .Values.schedulerName }}
      securityContext: {{ .Values.securityContext }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

