apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  labels:
    io.kompose.service: feelguuds-platform
  name: feelguuds-platform
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "9898"
    port: 9898
    targetPort: 9898
  - name: "9897"
    port: 9897
    targetPort: 9897
  selector:
    io.kompose.service: feelguuds-platform
status:
  loadBalancer: {}
