{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "platform.serviceAccountName" . }}
  labels:
    {{- include "platform.labels" . | nindent 4 }}
{{- end -}}
