{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "feelguuds-platform.serviceAccountName" . }}
  labels:
    {{- include "feelguuds-platform.labels" . | nindent 4 }}
{{- end -}}
