apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  containers:
  - env:
    - name: ES_JAVA_OPTS
      value: -Xms512m -Xmx512m
    - name: cluster.name
      value: jaeger-cluster
    - name: discovery.type
      value: single-node
    - name: http.host
      value: 0.0.0.0
    - name: transport.host
      value: 127.0.0.1
    - name: xpack.security.enabled
      value: "false"
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    name: elasticsearch
    ports:
    - containerPort: 9200
    - containerPort: 9300
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/elasticsearch/data
      name: elasticsearch-claim0
  restartPolicy: OnFailure
  volumes:
  - name: elasticsearch-claim0
    persistentVolumeClaim:
      claimName: elasticsearch-claim0
status: {}
