apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.jaeger.yaml convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-query
  name: jaeger-query
spec:
  ports:
  - name: "16686"
    port: 16686
    targetPort: 16686
  - name: "16687"
    port: 16687
    targetPort: 16687
  selector:
    io.kompose.service: jaeger-query
status:
  loadBalancer: {}
