apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-query
  name: jaeger-query
spec:
  containers:
  - args:
    - --log-level=debug
    env:
    - name: ES_SERVER_URLS
      value: http://elasticsearch:9200
    - name: JAEGER_ENDPOINT
      value: http://jaeger-collector:14268/api/traces
    - name: SPAN_STORAGE_TYPE
      value: elasticsearch
    - name: no_proxy
      value: localhost
    image: jaegertracing/jaeger-query:latest
    name: jaeger-query
    ports:
    - containerPort: 16686
    - containerPort: 16687
    resources: {}
  restartPolicy: OnFailure
status: {}
