apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-agent
  name: jaeger-agent
spec:
  containers:
  - args:
    - --reporter.type=grpc
    - --reporter.grpc.host-port=jaeger-collector:14250
    env:
    - name: ES_SERVER_URLS
      value: http://elasticsearch:9200
    - name: SPAN_STORAGE_TYPE
      value: elasticsearch
    image: jaegertracing/jaeger-agent:latest
    name: jaeger-agent
    ports:
    - containerPort: 5775
      protocol: UDP
    - containerPort: 6831
      protocol: UDP
    - containerPort: 6832
      protocol: UDP
    - containerPort: 5778
    resources: {}
  hostname: jaeger-agent
  restartPolicy: OnFailure
status: {}
