apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.jaeger.yaml convert -c
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-collector
  name: jaeger-collector
spec:
  ports:
  - name: "14269"
    port: 14269
    targetPort: 14269
  - name: "14268"
    port: 14268
    targetPort: 14268
  - name: "14267"
    port: 14267
    targetPort: 14267
  - name: "9411"
    port: 9411
    targetPort: 9411
  - name: "14250"
    port: 14250
    targetPort: 14250
  selector:
    io.kompose.service: jaeger-collector
status:
  loadBalancer: {}
