apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-collector
  name: jaeger-collector
spec:
  containers:
  - args:
    - --es.num-shards=1
    - --es.num-replicas=0
    - --log-level=error
    env:
    - name: ES_SERVER_URLS
      value: http://elasticsearch:9200
    - name: SPAN_STORAGE_TYPE
      value: elasticsearch
    image: jaegertracing/jaeger-collector:latest
    name: jaeger-collector
    ports:
    - containerPort: 14269
    - containerPort: 14268
    - containerPort: 14267
    - containerPort: 9411
    - containerPort: 14250
    resources: {}
  restartPolicy: OnFailure
status: {}
