apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c --file docker-compose.authn.yaml
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: auth-service-redis
  name: auth-service-redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    io.kompose.service: auth-service-redis
status:
  loadBalancer: {}
