version: '3.7'

services:
  # FeelguudsPlatform
  Platform:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    container_name: FeelguudsPlatform
    ports:
      - "9898:9898" # http port
      - "9897:9897" # grpc port
    restart: unless-stopped
    environment:
      - AUTHN_INTERNAL_PORT=3000
      - AUTHN_PORT=8000
    networks:
      - monitor-net
      - web
    volumes:
      - '.:/go/src/github.com/yoanyombapro1234/FeelguudsPlatform'
    env_file:
      - ../.env
    depends_on:
      - auth_service

networks:
  monitor-net:
    driver: bridge

volumes:
  postgres:
