apiVersion: v1
entries:
  authentication-service:
  - apiVersion: v1
    appVersion: 0.0.1
    created: "2021-10-12T06:17:16.537145216Z"
    description: Authentication Service Helm chart for Kubernetes
    digest: 601667ec2e39e62590952f0310fd226e46677fc83c2f7753fbeaf36cab838890
    home: https://github.com/yoanyombapro1234/FeelGuuds
    keywords:
    - docker-compose.keratin_authn
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: yaonyombapro@gmail.com
      name: yoanyomba
    name: authentication-service
    sources:
    - https://github.com/yoanyombapro1234/FeelGuuds
    urls:
    - https://yoanyombapro1234.github.io/FeelguudsPlatform/charts/authentication-service-0.0.1.tgz
    version: 0.0.1
  feelguuds-platform:
  - apiVersion: v1
    appVersion: 0.0.1
    created: "2021-10-12T06:17:16.538576242Z"
    description: Feelguuds Platforn Helm chart for Kubernetes
    digest: 47cabe784f5ab65e278ca92567025d5b3bc385d93bd2fa66be91bf8db679e4d9
    home: https://github.com/yoanyombapro1234/FeelGuuds
    icon: https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif
    keywords:
    - docker-compose.feelguuds_platform
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - email: yoanyombapro@gmail.com
      name: yoanyomba
    name: feelguuds-platform
    sources:
    - https://github.com/yoanyombapro1234/FeelGuuds
    urls:
    - https://yoanyombapro1234.github.io/FeelguudsPlatform/charts/feelguuds-platform-0.0.1.tgz
    version: 0.0.1
generated: "2021-10-12T06:17:16.535810791Z"
