// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal/merchant/merchant.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	internal/merchant/merchant.proto

It has these top-level messages:
	MerchantAccount
	Settings
	ItemSold
	Address
	Owner
	Tags
	Policy
	ReturnPolicy
	ShippingPolicy
*/
package models

import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = math.Inf
