apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.shopper.dep.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: shopper-component-db
  name: shopper-component-db
spec:
  ports:
  - name: "6001"
    port: 6001
    targetPort: 5432
  selector:
    io.kompose.service: shopper-component-db
status:
  loadBalancer: {}
