apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml -f docker-compose.authn.yaml -f docker-compose.merchant.dep.yaml
      -f docker-compose.shopper.dep.yaml convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: feelguuds-platform
  name: feelguuds-platform
spec:
  ports:
  - name: "9898"
    port: 9898
    targetPort: 9898
  - name: "9897"
    port: 9897
    targetPort: 9897
  selector:
    io.kompose.service: feelguuds-platform
status:
  loadBalancer: {}
