name: Integration

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: authentication_service
          POSTGRES_PASSWORD: authentication_service
          POSTGRES_DB: authentication_service
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      auth_service:
        image: keratin/authn-server:latest
        ports:
          - "8000:3000"
        env:
          DATABASE_URL: postgres://authentication_service:authentication_service@localhost:5432/authentication_service?sslmode=disable
          AUTHN_URL: http://localhost:8000
          APP_DOMAINS: localhost
          SECRET_KEY_BASE: secret
          REDIS_URL: redis://localhost:6379/11
          HTTP_AUTH_USERNAME: feelguuds
          HTTP_AUTH_PASSWORD: feelguuds
          ENABLE_SIGNUP: false
          ACCESS_TOKEN_TTL: 86400
          REFRESH_TOKEN_TTL: 2592000
          SESSION_KEY_SALT: feelguuds
          DB_ENCRYPTION_KEY_SALT: feelguuds
          USERNAME_IS_EMAIL: true
          PASSWORD_POLICY_SCORE: 2
          PASSWORD_CHANGE_LOGOUT: true
          PASSWORD_RESET_TOKEN_TTL: 1800
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: go version
      - run: go mod download
      - name: Running Containers
        run: docker ps -a
      - name: Run tests
        run: |
          go test \
            -race \
            -covermode=atomic \
            -coverprofile=coverage.out \
            ./...
      - name: Report coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
